### PR TITLE
Feature update django versions

### PR DESCRIPTION
**Pull request by DoroninaD**
* Add django-2.0, remove django-1.10
* Update deps (remove django-2.0, remove django-1.10)
* Update travis setup

### CODE REVIEW

**Comment by diox** [comment]
Have you tested it in the real world with django 2.0 ?

**Comment by DoroninaD** [comment]
Yes, it works in app with django 2.0

**Comment by vikalpj** [comment]
Can we merge this in ? Thanks!

**Comment by diox** [comment]
Sorry about the lack on movement on this. We can merge it yes. You'll have to bug us in a separate issue about making a new release with it though :)

**Pull request merged**
